zephyr-bindgen: update to latest bindgen compatible with Rust 1.70
0.70 requires a feature from Rust 1.77.

error[E0433]: failed to resolve: could not find `offset_of` in `mem`