ci: disable native_posix for 3.5, 3.6
9f1e4fa86c98ca5a80008080045bdc3b61efd5b9 broke including
<zephyr/posix/time.h>.

It was fixed in 6cf557d64a61d30352b6c50dbeab1dae4f3a67c1 which was only
backported to 3.7-branch as fe0b5ab37b1a1959e4457fee6e0ff0964176adee,
which doesn't currently have a point release.

Should be able to turn native_posix on for 3.7 if I can build from the
branch instead of the released 3.7.0 tag.

zephyr/include/zephyr/posix/posix_types.h:51:21: error: ‘pthread_attr_t’ undeclared here (not in a function); did you mean ‘pthread_attr’?