thread: Move extern static check into 'unsafe' code block due to compile error
error: use of extern static is unsafe and requires unsafe function or block (error E0133)